export const categories = [
  { label: 'Beauty', value: 'beauty' },
  { label: 'Fragrances', value: 'fragrances' },
  { label: 'Furniture', value: 'furniture' },
  { label: 'Groceries', value: 'groceries' },
  { label: 'Home Decoration', value: 'home-decoration' },
  { label: 'Kitchen Accessories', value: 'kitchen-accessories' },
  { label: 'Laptops', value: 'laptops' },
  { label: 'Mens Shirts', value: 'mens-shirts' },
  { label: 'Mens Shoes', value: 'mens-shoes' },
  { label: 'Mens Watches', value: 'mens-watches' },
  { label: 'Mobile Accessories', value: 'mobile-accessories' },
  { label: 'Motorcycle', value: 'motorcycle' },
  { label: 'Skin Care', value: 'skin-care' },
  { label: 'Smartphones', value: 'smartphones' },
  { label: 'Sports Accessories', value: 'sports-accessories' },
  { label: 'Sunglasses', value: 'sunglasses' },
  { label: 'Tablets', value: 'tablets' },
  { label: 'Tops', value: 'tops' },
  { label: 'Vehicle', value: 'vehicle' },
  { label: 'Womens Bags', value: 'womens-bags' },
  { label: 'Womens Dresses', value: 'womens-dresses' },
  { label: 'Womens Jewellery', value: 'womens-jewellery' },
  { label: 'Womens Shoes', value: 'womens-shoes' },
  { label: 'Womens Watches', value: 'womens-watches' },
];
